### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by bobzhang** [moonbitlang/core#50]
- [ ] map
- [ ] set
- [ ] hashmap
- [ ] hashset
- [ ] json
- [ ] mutable map // mutable map
- [ ] mutable set

**Comment by DiamondMofeng** [comment]
How about BinaryHeap👀

**Comment by bobzhang** [comment]
@DiamondMofeng contributions are welcome

**Comment by zxch3n** [comment]
Just created a PR for `sort` https://github.com/moonbitlang/core/pull/72

**Comment by peter-jerry-ye** [comment]
- [ ]  `reserve_capacity` and `shrink_to_fit` for vector/deque

**Comment by peter-jerry-ye** [comment]
- [ ] time api (may be an API similar to Java with `LocalDate` `LocalTime` `LocalDateTime` and `ZonedDateTime`

**Comment by He1pa** [comment]
stable sort  #225

**Comment by fantix** [comment]
Another reference for the time API: https://docs.edgedb.com/database/stdlib/datetime

**Comment by lgxbslgx** [comment]
If I want to claim a task you listed above, I need to read all the PRs and judge which task is been reviewing now. Also, I don't know which task has been already started by someone locally. So I suggest that all the tasks should have their own issues (so that the developers can assign them clearly) and link them in this issue. For example ( `json` and ` json5`)

> * [ ]  json  [Its issue]()  [Its PR]()
> * [ ]  json5  [Its issue]()  [Its PR]()

**Comment by jialunzhang-psu** [comment]
For coverage to go above 95%, we need to resolve an issue mentioned in #223, i.e., unreachable statements for exhaustiveness of pattern matching shouldn't be counted towards missing coverage.

**Comment by schizobulia** [comment]
好像并没有如何debug源码的介绍？
