### ISSUE TITLE
add `from_iter` function for collections

### ISSUE THREAD

**Issue by Yoorkin** [moonbitlang/core#744]
# Motivation

Collections can be created from an array using `T::from_array`. In some cases, when the initial elements originate from an iterator, users must first convert the iterator into an array before calling `T::from_array`. This process requires an additional array allocation. 

To avoid the additional allocation, we can introduce `T::from_iter[A](iter : Iter[A]) -> T` methods, allowing for the direct creation of collections from an iterator.

# Todo 

- [ ] array
- [ ] fixedarray
- [ ] bytes
     - change type of `Bytes::from_array` from `(Array[Int])->Bytes` to `(Array[Byte])->Bytes`
     - add new function `Bytes::from_iter(Iter[Byte])`
- [ ] deque
- [ ] hashmap
- [ ] hashset
- [ ] immut/array
- [ ] immut/hashmap
- [ ] immut/hashset
- [ ] immut/list
- [ ] immut/priority_queue
- [ ] immut/sorted_map
- [ ] immut/sorted_set
- [ ] priority_queue
- [ ] queue
- [ ] sorted_map
- [ ] sorted_set
